/**
 * '다시, 공간' 대구광역시 유휴시설 초기 데이터셋
 * 대구광역시 9개 구·군 기반의 현실감 있는 유휴공간 데이터
 */

const INITIAL_SPACES = [
  {
    id: "SPC-001",
    name: "삼덕 청년 예술창작 유휴창고",
    category: "ART",
    categoryName: "문화·예술",
    district: "중구",
    address: "대구광역시 중구 삼덕동2가 149-1",
    lat: 35.8642,
    lng: 128.6045,
    area: 142.5,
    pyeong: 43.1,
    deposit: 500,
    monthlyRent: 35,
    maintenanceFee: 5,
    status: "AVAILABLE",
    statusName: "이용 가능",
    remodelingStatus: "SUPPORT_ELIGIBLE",
    remodelingSupport: "대구 중구 도시재생 리모델링 보조금 최대 1,500만원 지원 대상",
    managingAgency: "대구광역시 중구 도시재생지원센터",
    agencyContact: "053-661-2851",
    photos: [
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "지상 1층 (단독 창고형)",
    structure: "철골 콘크리트조 (층고 4.8m)",
    parking: true,
    parkingSpaces: 4,
    utilities: ["수도", "전기(30kW 증설)", "개별 화장실", "광케이블 인터넷", "자체 진입로"],
    transportInfo: "대구 2호선 경대병원역 4번 출구 도보 5분",
    tags: ["높은 층고", "전시/공연", "예술가 특화", "주차 완비", "도시재생 지원"],
    description: "삼덕동 카페 골목 인근에 위치한 구 양곡 창고를 청년 예술인 및 문화 전시용으로 개방한 공간입니다. 4.8m의 높은 층고와 노출 콘크리트 마감으로 회화, 조각, 미디어아트 전시 및 소규모 복합문화 공연장으로 최적입니다.",
    features: [
      "자연 채광용 천창 설치 완료",
      "대형 화물 반입 가능한 슬라이딩 도어",
      "대구시 청년예술인 창작공간 임대료 50% 감면 지원 혜택 적용 가능"
    ],
    createdAt: "2026-07-10",
    views: 842,
    favoriteCount: 68
  },
  {
    id: "SPC-002",
    name: "복현 혁신 청년 스타트업 코워킹 베이스",
    category: "STARTUP",
    categoryName: "청년 창업",
    district: "북구",
    address: "대구광역시 북구 복현동 340-12",
    lat: 35.8925,
    lng: 128.6189,
    area: 88.0,
    pyeong: 26.6,
    deposit: 300,
    monthlyRent: 20,
    maintenanceFee: 8,
    status: "AVAILABLE",
    statusName: "이용 가능",
    remodelingStatus: "COMPLETED",
    remodelingSupport: "2025년 대구시 청년창업공간 뉴딜사업으로 전면 리모델링 완료",
    managingAgency: "대구창조경제혁신센터 / 경북대 도시재생추진단",
    agencyContact: "053-759-6380",
    photos: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "지상 2층",
    structure: "철근콘크리트 구조",
    parking: true,
    parkingSpaces: 6,
    utilities: ["중앙 냉난방", "초고속 GiGA 인터넷", "회의실(빔프로젝터)", "공용 탕비실", "도어락"],
    transportInfo: "경북대학교 북문 도보 3분, 버스정류장 1분",
    tags: ["스타트업", "경북대 인접", "리모델링 완료", "저렴한 임대료", "회의실 구비"],
    description: "경북대학교 북문 인근의 장기 공실 상가 건물을 청년 IT/테크 스타트업을 위해 스마트 오피스로 전면 개조한 유휴시설입니다. 데스크, 초고속 유무선망, 회의실 시설이 완비되어 있어 즉시 입주 가능합니다.",
    features: [
      "모든 사무가구(데스크, 인체공학 의자) 무상 대여",
      "초기 창업팀 전담 멘토링 프로그램 연계",
      "대구 청년창업 펀드 IR 데모데이 우선 참가 기회"
    ],
    createdAt: "2026-07-15",
    views: 1250,
    favoriteCount: 114
  },
  {
    id: "SPC-003",
    name: "대명동 음악·영상 복합 창작 스튜디오",
    category: "WORKSHOP",
    categoryName: "작업실",
    district: "남구",
    address: "대구광역시 남구 대명동 1892-5",
    lat: 35.8532,
    lng: 128.5831,
    area: 115.7,
    pyeong: 35.0,
    deposit: 400,
    monthlyRent: 30,
    maintenanceFee: 4,
    status: "AVAILABLE",
    statusName: "이용 가능",
    remodelingStatus: "SUPPORT_ELIGIBLE",
    remodelingSupport: "남구 대명공연문화거리 방음공사 지원사업 연계 가능",
    managingAgency: "대구광역시 남구 문화관광과",
    agencyContact: "053-664-2173",
    photos: [
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "지하 1층 (방음 특화)",
    structure: "철근콘크리트 라멘조",
    parking: false,
    parkingSpaces: 0,
    utilities: ["기본 흡음재 시공", "3상 380V 전력", "독립 환기시설", "수도설비", "보안 CCTV"],
    transportInfo: "대구 1호선 영대병원역 3번 출구 도보 7분, 대명공연거리 중심부",
    tags: ["방음 특화", "음악/영상 작업", "공연거리", "24시간 이용", "저렴한 월세"],
    description: "대명동 공연예술문화거리 내 위치한 유휴 지하공간입니다. 층고가 높고 소음 민원이 적어 음악 레코딩, 밴드 합주, 유튜브 영상 촬영, 공예 가공 등 소음이 발생하는 창작 작업실로 최적화되어 있습니다.",
    features: [
      "24시간 제약 없는 자유로운 창작 활동 보장",
      "대명공연예술제 및 지역 축제 협업 연계",
      "기본 전기용량 증설 완료로 고전력 장비 운용 용이"
    ],
    createdAt: "2026-07-18",
    views: 730,
    favoriteCount: 52
  },
  {
    id: "SPC-004",
    name: "동성로 르네상스 팝업 & 소상공인 스토어",
    category: "SHOP",
    categoryName: "소규모 상점",
    district: "중구",
    address: "대구광역시 중구 동성로2가 88-3",
    lat: 35.8698,
    lng: 128.5962,
    area: 52.8,
    pyeong: 16.0,
    deposit: 1000,
    monthlyRent: 60,
    maintenanceFee: 10,
    status: "RESERVED",
    statusName: "예약 중",
    remodelingStatus: "PARTIAL",
    remodelingSupport: "동성로 르네상스 프로젝트 상가 인테리어 500만원 바우처 제공",
    managingAgency: "대구광역시 원도심재생과",
    agencyContact: "053-803-3921",
    photos: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "지상 1층 (가시성 우수 통유리)",
    structure: "조적조 및 글래스 파사드",
    parking: false,
    parkingSpaces: 0,
    utilities: ["쇼룸형 LED 조명", "시스템 에어컨", "수도시설", "POS 설치대", "통유리 쇼윈도"],
    transportInfo: "대구 1·2호선 반월당역 13번 출구 도보 4분 / 중앙로역 2번 출구 도보 3분",
    tags: ["동성로 중심가", "유동인구 최다", "팝업스토어", "소상공인 쇼룸", "반월당역세권"],
    description: "동성로 핵심 상권 내 유휴 공실 점포를 청년 브랜드 팝업스토어 및 로컬 크리에이터 편집숍으로 지원하기 위한 공간입니다. 풍부한 유동인구와 뛰어난 집객력을 바탕으로 브랜드 런칭에 최적입니다.",
    features: [
      "통유리 전면 파사드로 시각적 노출 효과 극대화",
      "단기 팝업(1~3개월) 및 장기 임대 유연 계약 가능",
      "대구 로컬 청년 브랜드 페스타 우선 입점 혜택"
    ],
    createdAt: "2026-07-20",
    views: 2100,
    favoriteCount: 189
  },
  {
    id: "SPC-005",
    name: "비산동 행복나눔 사회적기업 복합허브",
    category: "SOCIAL",
    categoryName: "사회적기업",
    district: "서구",
    address: "대구광역시 서구 비산동 1240-8",
    lat: 35.8785,
    lng: 128.5672,
    area: 198.0,
    pyeong: 59.9,
    deposit: 600,
    monthlyRent: 40,
    maintenanceFee: 7,
    status: "AVAILABLE",
    statusName: "이용 가능",
    remodelingStatus: "SUPPORT_ELIGIBLE",
    remodelingSupport: "서구 도시재생 어울림플랫폼 개보수 지원 (최대 2,000만원)",
    managingAgency: "대구 서구 마을공동체지원센터",
    agencyContact: "053-663-2281",
    photos: [
      "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "지상 1~2층 전체",
    structure: "철근콘크리트 2층 건물",
    parking: true,
    parkingSpaces: 5,
    utilities: ["엘리베이터", "남녀 분리 화장실", "공용 커뮤니티홀", "주방 조리시설", "전기 온돌"],
    transportInfo: "원대역(3호선) 도보 8분, 서구청 5분 거리",
    tags: ["대형 공간", "사회적경제", "커뮤니티 홀", "마을기업", "주차 공간"],
    description: "서구 원도심 내 폐원된 옛 어린이집 건물을 사회적경제기업, 협동조합, 마을공동체를 위한 복합 공간으로 재생했습니다. 1층은 주민 카페 및 교육장, 2층은 사무실 및 작업장으로 구성 가능합니다.",
    features: [
      "넓은 마당과 옥상 텃밭 공간 보유",
      "사회적기업 인증 추진팀 임대료 추가 30% 감면",
      "지역 주민 대상 교육 및 플리마켓 개최 가능"
    ],
    createdAt: "2026-07-22",
    views: 620,
    favoriteCount: 45
  },
  {
    id: "SPC-006",
    name: "수성 알파시티 IT·소프트웨어 공유오피스",
    category: "OFFICE",
    categoryName: "사무실",
    district: "수성구",
    address: "대구광역시 수성구 대흥동 820-1",
    lat: 35.8398,
    lng: 128.6945,
    area: 72.5,
    pyeong: 21.9,
    deposit: 500,
    monthlyRent: 45,
    maintenanceFee: 6,
    status: "AVAILABLE",
    statusName: "이용 가능",
    remodelingStatus: "COMPLETED",
    remodelingSupport: "수성알파시티 디지털밸리 소프트웨어 인큐베이팅 지원",
    managingAgency: "대구디지털혁신진흥원 (DIP)",
    agencyContact: "053-655-7000",
    photos: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "지상 3층 (전망 우수)",
    structure: "최신 스마트 빌딩",
    parking: true,
    parkingSpaces: 10,
    utilities: ["서버랙실 구비", "24시간 지문인식 출입", "초고속 10G 전용망", "개별 냉난방", "샤워실"],
    transportInfo: "대구 2호선 대공원역 도보 10분, 수성알파시티 순환버스 2분",
    tags: ["IT기업 특화", "디지털밸리", "서버룸 구비", "쾌적한 환경", "주차 완비"],
    description: "대구 대표 ICT 거점인 수성알파시티 내 공공 지원시설 유휴 층을 AI, SaaS, 게임, 웹개발 등 IT/소프트웨어 스타트업 전용 독립 사무실로 제공합니다. 최첨단 네트워크 인프라와 쾌적한 연구 환경을 자랑합니다.",
    features: [
      "클라우드 크레딧 및 GPU 연산 서버 우선 바우처 지원",
      "DIP 주관 SW 전문 세미나 및 네트워킹 행사 무료 초청",
      "쾌적한 건물 옥상 정원 및 휴게 라운지 이용 가능"
    ],
    createdAt: "2026-07-25",
    views: 1540,
    favoriteCount: 132
  },
  {
    id: "SPC-007",
    name: "평리동 한옥 감성 빈집 문화살롱",
    category: "ART",
    categoryName: "문화·예술",
    district: "서구",
    address: "대구광역시 서구 평리동 1092-3",
    lat: 35.8712,
    lng: 128.5587,
    area: 99.2,
    pyeong: 30.0,
    deposit: 300,
    monthlyRent: 25,
    maintenanceFee: 3,
    status: "REMODELING",
    statusName: "리모델링 중",
    remodelingStatus: "IN_PROGRESS",
    remodelingSupport: "대구 빈집 정비사업 한옥 개보수 국비 100% 지원 공사 중",
    managingAgency: "대구광역시 서구청 도시재생과",
    agencyContact: "053-663-2771",
    photos: [
      "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "단층 한옥 (중정 마당 보유)",
    structure: "전통 목조 및 기와 구조",
    parking: false,
    parkingSpaces: 0,
    utilities: ["전통 대청마루", "시스템 통창 설치 예정", "온돌 난방", "조경 마당"],
    transportInfo: "서대구KTX역 차량 7분, 평리네거리 도보 5분",
    tags: ["전통 한옥", "중정 마당", "복합 문화공간", "원데이 클래스", "북카페"],
    description: "오랫동안 비어있던 근대 한옥 가옥을 대구시 빈집 살리기 사업을 통해 감성 문화살롱으로 재생 중인 공간입니다. 2026년 9월 리모델링 완공 예정이며 북카페, 찻집, 독립서점, 규방공예 공방 입주자를 모집합니다.",
    features: [
      "운치 있는 고즈넉한 중정과 대청마루 구조 보존",
      "입주자 맞춤형 인테리어 변경 사전 협의 가능",
      "서대구 KTX역 개통에 따른 관광객 유입 기대"
    ],
    createdAt: "2026-07-28",
    views: 980,
    favoriteCount: 88
  },
  {
    id: "SPC-008",
    name: "성당못 청년 메이커스 공예 목공 팩토리",
    category: "WORKSHOP",
    categoryName: "작업실",
    district: "달서구",
    address: "대구광역시 달서구 성당동 612-4",
    lat: 35.8384,
    lng: 128.5492,
    area: 165.0,
    pyeong: 49.9,
    deposit: 500,
    monthlyRent: 35,
    maintenanceFee: 5,
    status: "AVAILABLE",
    statusName: "이용 가능",
    remodelingStatus: "SUPPORT_ELIGIBLE",
    remodelingSupport: "달서구 청년공방 창업 시설비 700만원 보조",
    managingAgency: "달서구 경제지원과",
    agencyContact: "053-667-2641",
    photos: [
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "지상 1층 (트럭 진출입 가능)",
    structure: "강구조 / 에폭시 바닥 시공",
    parking: true,
    parkingSpaces: 3,
    utilities: ["산업용 전력(50kW)", "집진기 설치 배관", "에어 콤프레셔 라인", "오폐수 정화조"],
    transportInfo: "대구 1호선 서부정류장역 도보 6분, 두류공원 인접",
    tags: ["목공/가구", "메이커스페이스", "산업용 전기", "장비 반입 용이", "두류공원 인접"],
    description: "과거 철공 부자재 창고로 쓰이던 유휴 부지를 리사이클링 가구, 목공예, 금속공예, 도자 제작 등 하드웨어 제작 메이커를 위한 전문 작업 팩토리로 제공합니다. 소음과 분진 처리에 최적화되어 있습니다.",
    features: [
      "1톤 트럭 내부 진입 및 하역 가능한 광폭 셔터",
      "집진 설비 및 고출력 전력 시스템 완비",
      "두류공원 청년 축제 아트마켓 우선 판매 부스 지원"
    ],
    createdAt: "2026-08-01",
    views: 890,
    favoriteCount: 71
  },
  {
    id: "SPC-009",
    name: "신암동 뉴딜 도심 스마트 팜 & 로컬 F&B 실습실",
    category: "STARTUP",
    categoryName: "청년 창업",
    district: "동구",
    address: "대구광역시 동구 신암동 480-15",
    lat: 35.8812,
    lng: 128.6251,
    area: 120.0,
    pyeong: 36.3,
    deposit: 400,
    monthlyRent: 28,
    maintenanceFee: 6,
    status: "AVAILABLE",
    statusName: "이용 가능",
    remodelingStatus: "COMPLETED",
    remodelingSupport: "신암재정비촉진지구 스마트어반팜 시설 전액 구축 완료",
    managingAgency: "대구 동구 도시재생지원센터",
    agencyContact: "053-662-2691",
    photos: [
      "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "지상 1층 + 온실형 옥상",
    structure: "경량 철골조 및 스마트 온실",
    parking: true,
    parkingSpaces: 2,
    utilities: ["수경재배 LED 시스템", "상하수도 직결", "주방 후드 및 가스", "정온 항온 시스템"],
    transportInfo: "대구 1호선 신암역 도보 5분, 동대구역 복합환승센터 10분",
    tags: ["스마트팜", "로컬푸드", "F&B 창업", "동대구역세권", "주방설비 완비"],
    description: "동구 노후 주거지 재생 과정에서 확보된 공공 부지를 도심형 수경재배 스마트팜 및 청년 외식업 R&D 실습실로 조성한 유휴공간입니다. 샐러드, 친환경 식음료, 밀키트 창업을 준비하는 청년팀을 환영합니다.",
    features: [
      "스마트팜 자동 환경제어 IOT 센서 시스템 탑재",
      "위생등급 인증 가능한 오픈 키친 및 베이킹 오븐 보유",
      "동대구역 로컬 특산물 팝업존 판매 연계"
    ],
    createdAt: "2026-08-03",
    views: 1120,
    favoriteCount: 96
  },
  {
    id: "SPC-010",
    name: "다사읍 금호강변 복합문화 청년 라운지",
    category: "ART",
    categoryName: "문화·예술",
    district: "달성군",
    address: "대구광역시 달성군 다사읍 매곡리 120-1",
    lat: 35.8589,
    lng: 128.4612,
    area: 210.0,
    pyeong: 63.5,
    deposit: 600,
    monthlyRent: 40,
    maintenanceFee: 8,
    status: "AVAILABLE",
    statusName: "이용 가능",
    remodelingStatus: "COMPLETED",
    remodelingSupport: "달성문화재단 공간 운영비 및 전시 대관료 일부 지원",
    managingAgency: "달성문화재단 / 달성군청",
    agencyContact: "053-659-4282",
    photos: [
      "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "단독 2층 건물 전체",
    structure: "통유리 뷰 철근 콘크리트",
    parking: true,
    parkingSpaces: 12,
    utilities: ["넓은 주차장", "금호강 조망 테라스", "음향 앰프 시스템", "카페테리아 바"],
    transportInfo: "대구 2호선 문양역 도보 10분, 강변 자전거길 직결",
    tags: ["리버뷰", "대규모 공간", "문화예술", "주차 완비", "힐링 창작"],
    description: "금호강변의 수려한 자연경관을 마주하고 있는 유휴 폐건물을 청년 복합 문화 라운지 및 아트 레지던시로 탈바꿈했습니다. 전시장, 공연장, 북카페, 요가/명상 스튜디오 등 다목적 활용이 가능합니다.",
    features: [
      "금호강 파노라마 전망을 누릴 수 있는 2층 루프탑 테라스",
      "대형 버스 주차 가능한 넉넉한 전용 주차 공간",
      "지역 주민 및 관광객 연계 주말 아트 플리마켓 상시 개최"
    ],
    createdAt: "2026-08-05",
    views: 1450,
    favoriteCount: 140
  },
  {
    id: "SPC-011",
    name: "군위 삼국유사 테마 청년 로컬 크리에이터 기지",
    category: "STARTUP",
    categoryName: "청년 창업",
    district: "군위군",
    address: "대구광역시 군위군 군위읍 동부리 320",
    lat: 36.2415,
    lng: 128.5721,
    area: 150.0,
    pyeong: 45.4,
    deposit: 200,
    monthlyRent: 15,
    maintenanceFee: 2,
    status: "AVAILABLE",
    statusName: "이용 가능",
    remodelingStatus: "COMPLETED",
    remodelingSupport: "대구 편입 군위군 청년 정착 장려금 및 공간 무상 지원 혜택",
    managingAgency: "군위군 농촌활력과 / 대구 청년센터",
    agencyContact: "054-380-6000",
    photos: [
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "지상 1층 단층 (옛 보건지소 리모델링)",
    structure: "경량 철골조",
    parking: true,
    parkingSpaces: 8,
    utilities: ["주거 겸용 원룸 구비", "공용 주방", "인터넷", "회의 테이블", "넓은 앞마당"],
    transportInfo: "군위 버스터미널 도보 5분, 중앙고속도로 군위IC 10분",
    tags: ["로컬크리에이터", "워케이션", "초저렴 임대료", "주거 연계", "군위 특화"],
    description: "대구광역시에 새롭게 편입된 군위군의 유휴 공공시설을 청년 로컬 크리에이터와 귀촌 창업가를 위한 베이스캠프로 조성했습니다. 로컬 콘텐츠 기획, 농산물 브랜딩, 워케이션 오피스로 이상적입니다.",
    features: [
      "월 15만원의 파격적인 초저렴 임대료 및 청년 정착 지원금 연계",
      "업무와 임시 주거가 동시에 가능한 숙소 연계형 시설",
      "대구-군위 통합 기념 로컬 비즈니스 프로젝트 지원"
    ],
    createdAt: "2026-08-08",
    views: 780,
    favoriteCount: 65
  },
  {
    id: "SPC-012",
    name: "만촌동 청년 에듀테크 & 북스터디 라운지",
    category: "OFFICE",
    categoryName: "사무실",
    district: "수성구",
    address: "대구광역시 수성구 만촌동 1040-1",
    lat: 35.8571,
    lng: 128.6482,
    area: 75.0,
    pyeong: 22.7,
    deposit: 500,
    monthlyRent: 42,
    maintenanceFee: 5,
    status: "AVAILABLE",
    statusName: "이용 가능",
    remodelingStatus: "COMPLETED",
    remodelingSupport: "수성구 청년 미래인재 육성 공간 인테리어 완료",
    managingAgency: "수성구청 청년여성가족과",
    agencyContact: "053-666-2621",
    photos: [
      "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1000&q=80"
    ],
    floor: "지상 2층",
    structure: "철근콘크리트",
    parking: true,
    parkingSpaces: 4,
    utilities: ["전자칠판 완비", "소음 차단 부스 3실", "기가 와이파이", "개별 냉난방", "커피 머신"],
    transportInfo: "대구 2호선 만촌역 도보 4분, 범어네거리 1정거장",
    tags: ["수성구 명문학군", "에듀테크", "스터디룸", "세미나실", "역세권"],
    description: "수성구 학원가 인근의 유휴 공간을 교육 콘텐츠 개발, 에듀테크 스타트업, 비대면 튜터링 및 소규모 청년 세미나를 위한 스마트 라운지로 탈바꿈한 공간입니다.",
    features: [
      "화상 회의 및 온라인 강의 녹화 방음 부스 구비",
      "만촌역 초역세권으로 대중교통 접근성 최상",
      "수성구 평생학습원 교육 프로그램 공동 운영 기회"
    ],
    createdAt: "2026-08-10",
    views: 1100,
    favoriteCount: 95
  }
];

// 공통 코드 및 메타데이터 정의
const COMMON_CODES = {
  USER_TYPES: [
    { code: "GENERAL", name: "일반 사용자 (청년/창업/예술)" },
    { code: "PROVIDER", name: "공간 제공자 (건물주/기관)" },
    { code: "ADMIN", name: "관리자 (대구광역시/운영사)" }
  ],
  CATEGORIES: [
    { code: "STARTUP", name: "청년 창업", icon: "rocket", color: "#10B981" },
    { code: "SHOP", name: "소규모 상점", icon: "shopping-bag", color: "#F59E0B" },
    { code: "OFFICE", name: "사무실", icon: "briefcase", color: "#3B82F6" },
    { code: "ART", name: "문화·예술", icon: "palette", color: "#8B5CF6" },
    { code: "WORKSHOP", name: "작업실", icon: "hammer", color: "#EC4899" },
    { code: "SOCIAL", name: "사회적기업", icon: "heart-handshake", color: "#14B8A6" }
  ],
  DISTRICTS: [
    "중구", "동구", "서구", "남구", "북구", "수성구", "달서구", "달성군", "군위군"
  ],
  STATUSES: [
    { code: "AVAILABLE", name: "이용 가능", badgeClass: "badge-success" },
    { code: "RESERVED", name: "예약 중", badgeClass: "badge-warning" },
    { code: "IN_USE", name: "이용 중", badgeClass: "badge-info" },
    { code: "REMODELING", name: "리모델링 중", badgeClass: "badge-purple" },
    { code: "UNAVAILABLE", name: "이용 불가", badgeClass: "badge-danger" }
  ]
};

// 초기 공공데이터 연동 시뮬레이션 로그 및 통계
const INITIAL_DATA_SYNC_LOGS = [
  { timestamp: "2026-08-14 09:30:12", source: "대구 공공데이터 포털 API", status: "SUCCESS", count: 42, note: "대구시 공유재산 유휴지 API 연동 완료" },
  { timestamp: "2026-08-14 11:15:00", source: "도시재생 웹 크롤러", status: "SUCCESS", count: 18, note: "구·군별 빈집 실태조사 공시 수집" },
  { timestamp: "2026-08-14 14:00:22", source: "데이터 정제 엔진", status: "SUCCESS", count: 60, note: "결측치 보정 및 중복 주소 8건 자동 병합 완료" }
];
